### ISSUE TITLE
create-react-microservice command with @notated npm org cause failure

### ISSUE THREAD

**Issue by Romischart** [ImmoweltGroup/create-react-microservice#46]
### Describe the problem:
Running create-react-microservice with @ notated org, appends instantly a second `@`, for example in cli configuration on creating react microservice we use `@tesorg` after hitting enter the cli appends a second `@` to the name `@@testorg/`. This cause in the `yarn install` process a error `package.json: Name contains illegal characters`

#### Steps to reproduce:
```sh
create-react-microservice my-fancy-ui
What is the preffered license for the mono repository and its packages? MIT
What is the NPM organization scope for the mono repositories packages? @testorg
```

#### Observed Results:
```sh
create-react-microservice » Error: Command failed: yarn install
error package.json: Name contains illegal characters
```

**Comment by Inkdpixels** [comment]
fixed by 797a46b8ee80816aff4dd419c1db2df631f6ec1b
